# Machine Agent Win
# machine_agent_dest_folder_win: C:/appdynamics/machine-agent
machine_agent_monitor_folder_win: "{{ machine_agent_dest_folder_win }}/monitor"
temp_dir: /tmp

# Machine Agent Linux
# machine_agent_dest_folder_linux: /opt/appdynamics/machine-agent
machine_agent_monitor_folder_linux: "{{ machine_agent_dest_folder_linux }}/monitor/"

# Server visibility
sim_enabled: "false"

# AppDynamics user on target machine 
create_appdynamics_user: yes
appdynamics_user_id: "" # UID, empty by default
appdynamics_group_id: "" # GID, empty by default
