---
- hosts: all
  tasks:

    - name: Include variables for the controller settings
      include_vars: vars/controller.yaml
      
    - name: Include variables for JFrog Artifactory settings
      include_vars: vars/artifactory.yaml

    - include_role:
        name: machine
      vars:
        # Define Agent Type and Version
        agent_version: 21.9.0.3184 #update this when upgrading
        agent_type: machine #update this when upgrading
        machine_hierarchy: "AppName|Owners|Test|" # Make sure it ends with a |  #Update this as well depending on hierarchy
        sim_enabled: "true"
        agent_log_level: "debug"

        # config properties docs - https://docs.appdynamics.com/display/latest/Machine+Agent+Configuration+Properties
        # Can be used to configure the proxy for the agent 
        # mind the space between each property for proxies - Optional - eg: -Dappdynamics.http.proxyHost=IP address -Dappdynamics.http.proxyPort=9090
        # check with ps -ef | grep machine if Machine agent not appearing
        java_system_properties: "" 
