---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: "Add {{ appdynamics_user }} user to wheel group"
  user:
    name: "{{ appdynamics_user }}"
    groups: wheel
    append: yes
    state: present
