---
- name: Make sure we have a '"{{ appdynamics_user }}"' group with GID
  group:
    name: "{{ appdynamics_user }}"
    state: present
    gid: "{{ appdynamics_group_id }}"
  when: (appdynamics_group_id is defined) and (appdynamics_group_id|length > 0)

- name: Make sure we have a '"{{ appdynamics_user }}"' group without GID
  group:
    name: "{{ appdynamics_user }}"
    state: present
  when: (appdynamics_group_id is not defined) or (appdynamics_group_id|length == 0)

- name: Allow '"{{ appdynamics_user }}"' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ appdynamics_user }}'
    line: '%{{ appdynamics_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: "Add {{ appdynamics_user }} user to {{ appdynamics_user }} group with UID"
  user:
    name: "{{ appdynamics_user }}"
    groups: 
      - "{{ appdynamics_user }}"
    append: yes
    uid: "{{ appdynamics_user_id }}"
    state: present
  when: (appdynamics_user_id is defined) and (appdynamics_user_id|length > 0)

- name: "Add {{ appdynamics_user }} user to {{ appdynamics_user }} group without UID"
  user:
    name: "{{ appdynamics_user }}"
    groups: 
      - "{{ appdynamics_user }}"
    append: yes
    state: present
  when: (appdynamics_user_id is not defined) or (appdynamics_user_id|length == 0)
