
---

- name: Create subdirectory for custom extension
  win_file:
    path: "{{ machine_agent_dest_folder_win }}/monitors/customextensions"
    state: directory

  #  - name: Download custom extension 
      #  win_get_url:
      #     url: '{{ af_env }}/{{repo}}/{{extension_file}}'
      #     dest: "{{ machine_agent_dest_folder_linux }}/monitors/customextensions"
      #     username: "{{ username }}"
      #     password: "{{ password }}"
      #     force: true
      #   no_log: true #To prevent passwords to be on logs
      #   changed_when: false
      #   register: result
      #   failed_when: result.status_code != 200

      # - name: Unzip machine agent file
      #   win_unzip:
      #     src: "{{ machine_agent_dest_folder_win }}/{{ ma_agent_dest_file }}"
      #     dest: "{{ machine_agent_dest_folder_linux }}/monitors/customextensions"
      #     remote_src: yes
      #   changed_when: false

  #  - name: Install monitor.xml file
  #   file:
  #     path: ""
  #     state: absent
  #   changed_when: false

