
---

#Create new directory 
#Download script (is it zip file?)
#Create monitor.xml file



  - name: Create subdirectory for custom extension
    file:
      path: "{{ machine_agent_dest_folder_linux }}/monitors/customextensions"
      state: directory
      mode: 0755

  #Is there a difference in custom extension for windows/linux?
  # - name: Adjust the Machine agent file name to match the target OS
  #   set_fact:
  #     extension_file: "" #Confirm naming
  #   when: ansible_os_family == 'RedHat' or  ansible_os_family == 'Debian'

  # - name: Download custom extension 
  #     get_url:
  #       url: '{{artifactory_url}}/{{extension_file}}'
  #       dest: "{{ machine_agent_dest_folder_linux }}/monitors/customextensions"
  #       username: "{{ username }}"
  #       password: "{{ password }}"
  #       force: true
  #     no_log: true #To prevent passwords to be on logs
  #     changed_when: false
  #     register: result
  #     failed_when: result.status_code != 200

  - name: Unzip the custom extension file
    unarchive:
      src:  "{{ machine_agent_dest_folder_linux }}/monitors/customextensions"
      dest: "{{ machine_agent_dest_folder_linux }}/monitors/customextensions"
      owner: "{{ appdynamics_user }}"
      group: "{{ appdynamics_user }}"
      mode: 0755
      remote_src: yes
    changed_when: false

