
---

- name: Create subdirectory for custom extension
  win_file:
    path: "{{ machine_agent_dest_folder_win }}/monitors/customextensions"
    state: directory

#Is there a difference in custom extension for windows/linux?
# - name: Adjust the Machine agent file name to match the target OS
#   set_fact:
#     extension_file: "" #Confirm naming
#   when: ansible_os_family == 'Windows' and agent_type == 'machine'

- name: Copy file with owner and permissions (testing on local)
  copy:
    src: 
    dest: "{{ machine_agent_dest_folder_win }}/monitors/customextensions"
    mode: 0755
    changed_when: false
    register: result


# - name: Download custom extension - artifactory
#     win_get_url:
#       url: '{{artifactory_url}}/{{extension_file}}'
#       dest: "{{ machine_agent_dest_folder_win }}/monitors/customextensions"
#       username: "{{ username }}"
#       password: "{{ password }}"
#       force: true
#     no_log: true #To prevent passwords to be on logs
#     changed_when: false
#     register: result
#     failed_when: result.status_code != 200

- name: Unzip custom extension file
  win_unzip:
    src: "{{ machine_agent_dest_folder_win }}/monitors/customextensions"
    dest: "{{ machine_agent_dest_folder_win }}/monitors/customextensions"
    remote_src: yes
  changed_when: false