---

  - name: Add the Agent as a Service using Systemd
    become: true
    template:
      src: templates/appdynamics-machine-agent.service.j2
      dest: /etc/systemd/system/appdynamics-machine-agent.service
      force: true
      owner: root # In cases when Machine Agent must not run as root, you may change it.
      group: root
      mode: 0644
    register: machine_agent_systemd_result

  - name: Enable the Machine Agent to start at system startup
    become: true
    systemd:
      name: appdynamics-machine-agent
      enabled: yes
      force: true # Force it to override existing symlink incase of an upgrade
      masked: no

  # Reload systemd if it is an upgrade or re-installation
  - name:  Reload systemd configs
    become: true
    systemd:
      daemon_reload: yes
    #when: previous_agent.stat.exists

  - name: Start the agent service
    become: true
    systemd:
      name: appdynamics-machine-agent
      state: restarted
      daemon_reload: yes
    changed_when: false

  - name: Make sure the service is running
    command: systemctl status appdynamics-machine-agent
    register: result
    ignore_errors: yes
    changed_when: false

  - name: Show Machine Agent status
    debug:
      var: result

  - name: Clean up - remove {{ ma_agent_dest_file }}
    become: true
    file:
      path: "{{ machine_agent_dest_folder_linux }}/{{ ma_agent_dest_file }}"
      state: absent
    changed_when: false
