---
- name: Controller URL must be provided
  fail:
    msg: "The variable 'controller_host_name' is empty"
  when: (controller_host_name is not defined) or (controller_host_name|length == 0)

# Download Agent
- include_tasks: download_machine_agent_linux.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- include_tasks: download_machine_agent_win.yml
  when: ansible_os_family == 'Windows'

# Download and Configure Custom Extensions
- include_tasks: configure_custom_extensions_linux.yml
  when: enable_custom_extensions | bool == True and (ansible_os_family == 'RedHat' or ansible_os_family == 'Debian')

- include_tasks: configure_custom_extensions_win.yml
  when: enable_custom_extensions | bool == True and ansible_os_family == 'Windows'

# Install machine agent
- include_tasks: install_machine_agent_linux.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- include_tasks: install_machine_agent_win.yml
  when: ansible_os_family == 'Windows'